### ISSUE TITLE
Can't render Image

### ISSUE THREAD

**Issue by shepherd1530** [nodegui/react-nodegui#158]
I am trying to render an image but I can't quite figure out to do it properly. I tried to follow the examples from the repo but i still get an error.

```
const rootDir = path.resolve(__dirname, "../");
const assetUrl = path.resolve(rootDir, "src/assets/");

const Home = (props) => {
  const imageUrl = `${path.resolve(assetUrl, `${'welcome'}.jpg`)}`;
  return (
    <>
      <Image
        id="img"
        aspectRatioMode={AspectRatioMode.KeepAspectRatio}
        src={imageUrl}
      />
    </>
  )
}
```
```
Error: Bad URL protocol: c:
    at C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:13538:15
    at new Promise (<anonymous>)
    at CentraRequest.send (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:13465:10)
    at Object.phin [as default] (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:22979:871)
    at C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11759:45
    at Generator.next (<anonymous>)
    at C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11674:71
    at new Promise (<anonymous>)
    at ./node_modules/@nodegui/react-nodegui/dist/components/Image/RNImage.js.__awaiter (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11670:12)
    at getLoadedPixmap (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11756:12)
```
And if i load the image react way like

```
const im = require('../assets/welcome.jpg')

<Image
        id="img"
        aspectRatioMode={AspectRatioMode.KeepAspectRatio}
        src={im}
      />
```
i get 
```
Error: A string was expected
    at QPixmap.load (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:5541:28)
    at C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11764:20
    at Generator.next (<anonymous>)
    at C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11674:71
    at new Promise (<anonymous>)
    at ./node_modules/@nodegui/react-nodegui/dist/components/Image/RNImage.js.__awaiter (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11670:12)
    at getLoadedPixmap (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11756:12)
    at Object.set src [as src] (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11691:13)
    at Function.assign (<anonymous>)
    at setImageProps (C:\Users\SAM\Documents\React\GUIEx\JumpStart\dist\index.js:11707:12)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux or Windows] Windows 10
 - NodeGUI version 0.13.1
 - React NodeGUI version 0.4.0

**Comment by master-atul** [comment]
Hi @shepherd1530 

You need to use
```
import imageUrl from "../assets/demo.png";
```
instead of require with the current webpack setup. 

Webpack basically copies the image over to dist folder and sets imageUrl to the filepath of copied image.

Webpack doesnt do this when using require to load the image.

**Comment by master-atul** [comment]
To check this you can console.log the imageurl and see the result.

**Comment by shepherd1530** [comment]
@master-atul that cleared the console error but now i get 
 `QPixmap::scaled: Pixmap is a null pixmap` with a blank screen.

**Comment by master-atul** [comment]
could you post the `console.log(imageUrl)` result ?

**Comment by shepherd1530** [comment]
**19f64edf18144b243d70e631dd1043be.jpg**

**Comment by master-atul** [comment]
can you post your webpack.config file also please ?

**Comment by shepherd1530** [comment]
```
const path = require("path");
const webpack = require("webpack");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

module.exports = (env, argv) => {
  const config = {
    mode: "production",
    entry: ["./src/index.js"],
    target: "node",
    output: {
      path: path.resolve(__dirname, "dist"),
      filename: "index.js"
    },
    node: {
      __dirname: true,
      __filename: true
    },
    module: {
      rules: [
        {
          test: /\.(j|t)sx?$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
            options: { cacheDirectory: true, cacheCompression: false }
          }
        },
        {
          test: /\.(png|jpe?g|gif|svg|bmp)$/i,
          use: [{ loader: "file-loader" }]
        },
        {
          test: /\.node/i,
          use: [
            {
              loader: "native-addon-loader",
              options: {
                name: "[name]-[hash].[ext]"
              }
            }
          ]
        }
      ]
    },
    plugins: [],
    resolve: {
      extensions: [".tsx", ".ts", ".js", ".jsx", ".json"]
    }
  };

  if (argv.mode === "development") {
    config.mode = "development";
    config.plugins.push(new webpack.HotModuleReplacementPlugin());
    config.plugins.push(new ForkTsCheckerWebpackPlugin());
    config.devtool = "source-map";
    config.watch = true;
    config.entry.unshift("webpack/hot/poll?100");
  }

  if (argv.p) {
    config.plugins.push(new CleanWebpackPlugin());
  }
  return config;
};

```

**Comment by master-atul** [comment]
yep so can you modfiy
```
module: {
      rules: [
        {
          test: /\.(j|t)sx?$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
            options: { cacheDirectory: true, cacheCompression: false }
          }
        },
        {
          test: /\.(png|jpe?g|gif|svg|bmp|otf)$/i,
          use: [{
            loader: "file-loader",
            options: {
              publicPath: "dist"
            }
          }]
        },
        {
```

**Comment by master-atul** [comment]
also you can try removing the polyfills for __dirname and __filename
```
node: {
      __dirname: false,
      __filename: false
    },
```

**Comment by shepherd1530** [comment]
@master-atul am still gettng the same error even with the modifications and when I check the dist folder the renamed images are there.

**Comment by master-atul** [comment]
Have you tried putting absoulute image paths instead? 
Also after modifying webpack config (you will need to restart the webpack server aswell)

**Comment by shepherd1530** [comment]
Restarting the webpack dev server did the trick. Thanks a lot.
