### ISSUE TITLE
npm install failed on windows

### ISSUE THREAD

**Issue by lovelyJason** [nodegui/react-nodegui#311]
**Describe the bug**
I make sure I was installed cmake on windows, and then I used 'npm install' on the repo 'https://github.com/nodegui/react-nodegui-starter' project.It failed and throw the error like these:

`
> @nodegui/qode@2.1.0 postinstall D:\projects\react-nodegui-starter\node_modules\@nodegui\qode
> node install.js

Cached archive already exists at C:\Users\kingdee\AppData\Local\qode-nodejs\Cache\qode-win32-x64-v2.1.0.tar.gz. Skipping download....
Extracting C:\Users\kingdee\AppData\Local\qode-nodejs\Cache\qode-win32-x64-v2.1.0.tar.gz to D:\projects\react-nodegui-starter\node_modules\@nodegui\qode\binaries ...
Error while setting up Qode:  ZlibError: zlib: unexpected end of file
    at Unzip.<anonymous> (D:\projects\react-nodegui-starter\node_modules\minizlib\index.js:171:54)
    at Unzip.emit (events.js:326:22)
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8)
    at processChunkSync (zlib.js:429:12)
    at Unzip.ZlibBase._processChunk (zlib.js:404:12)
    at Unzip.write (D:\projects\react-nodegui-starter\node_modules\minizlib\index.js:147:30)
    at Unzip.flush (D:\projects\react-nodegui-starter\node_modules\minizlib\index.js:105:10)
    at Unzip.end (D:\projects\react-nodegui-starter\node_modules\minizlib\index.js:111:10)
    at Unpack.end (D:\projects\react-nodegui-starter\node_modules\tar\lib\parse.js:476:21)
    at Yallist.<anonymous> (D:\projects\react-nodegui-starter\node_modules\minipass\index.js:396:18) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: 'C:\\Users\\kingdee\\AppData\\Local\\qode-nodejs\\Cache\\qode-win32-x64-v2.1.0.tar.gz',
  cwd: 'D:\\projects\\react-nodegui-starter\\node_modules\\@nodegui\\qode\\binaries',
  tarCode: 'TAR_ABORT'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/qode@2.1.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/qode@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - React NodeGUI version : 0.9.0
 - OS Version : windows10

**Comment by lovelyJason** [comment]
Why don't you call me back?

**Comment by HAKANKOKCU** [comment]
they seems like never gonna fix it
