### ISSUE TITLE
react nodegui call stack exceeded error when using GridView/ BoxView components

### ISSUE THREAD

**Issue by jsilva23** [nodegui/react-nodegui#359]
> react-nodegui-starter@1.0.0 start
> qode ./dist/index.js

The above error occurred in the <gridview> component:
    in gridview (created by App)
    in mainwindow (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
/home/jsilva/Documents/react-nodegui-starter/dist/index.js:37888
      throw error;
      ^

RangeError: Maximum call stack size exceeded
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18051:15)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)
    at RNGridView.get layout [as layout] (/home/jsilva/Documents/react-nodegui-starter/dist/index.js:18052:21)

**Comment by asjur** [comment]
This is still an issue, occurred with both BoxView and GridView.

**Comment by DeDu-OS** [comment]
> This is still an issue, occurred with both BoxView and GridView.

I'm also having the same issue as of the time of posting this. If it's us, a little direction from the devs would be helpful.

**Comment by ProjectInfinity** [comment]
Seems like this project is a bit unmaintained.

**Comment by ivxvm** [comment]
This issue is still here.
