### ISSUE TITLE
Running for the second time no Macbook M1

### ISSUE THREAD

**Issue by ithustle** [nodegui/react-nodegui#361]
**Describe the bug**

````
$ qode --inspect ./dist/index.js
Debugger listening on ws://127.0.0.1:9229/a4a7a5f8-39a3-47b8-9b28-3781c9b14774
For help, see: https://nodejs.org/en/docs/inspector
/Users/celiogarcia/dev/desktop/limpo2/dist/index.js:77555
/******/ 			throw e;
         			^

Error: dlopen(/Users/celiogarcia/dev/desktop/limpo2/dist/nodegui_core-20a2313f154fad6d99a9d6b1fb40d713.node, 1): no suitable image found.  Did find:
	/Users/celiogarcia/dev/desktop/limpo2/dist/nodegui_core-20a2313f154fad6d99a9d6b1fb40d713.node: mach-o, but wrong architecture
	/Users/celiogarcia/dev/desktop/limpo2/dist/nodegui_core-20a2313f154fad6d99a9d6b1fb40d713.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1154:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object../node_modules/@nodegui/react-nodegui/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node (/Users/celiogarcia/dev/desktop/limpo2/dist/index.js:45335:18)
    at __webpack_require__ (/Users/celiogarcia/dev/desktop/limpo2/dist/index.js:77552:33)
    at fn (/Users/celiogarcia/dev/desktop/limpo2/dist/index.js:77705:21)
    at Object../node_modules/@nodegui/react-nodegui/node_modules/@nodegui/nodegui/dist/lib/utils/addon.js (/Users/celiogarcia/dev/desktop/limpo2/dist/index.js:37708:15)
    at __webpack_require__ (/Users/celiogarcia/dev/desktop/limpo2/dist/index.js:77552:33) {
  code: 'ERR_DLOPEN_FAILED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Desktop (please complete the following information):**
 - OS: macOS Apple M1, 
 - NodeGUI version: ^0.37.3
 - React NodeGUI version: ^0.13.0
 - OS Version: Big Sur 11.4

**Additional context**

**Comment by a7ul** [comment]
have you followed this guide here for M1: https://docs.nodegui.org/docs/guides/getting-started#using-your-own-custom-qt-installation-optional

**Comment by ithustle** [comment]
@a7ul, I realize that I've tried yesterday and today I was able to run once but after updated all dependencies and installed one I cannot run the app.

**Comment by ithustle** [comment]
Now, I'm having this issue

```
-- Configuring incomplete, errors occurred!
See also "/Users/celiogarcia/dev/desktop/toqueplay/node_modules/@nodegui/nodegui/build/CMakeFiles/CMakeOutput.log".
See also "/Users/celiogarcia/dev/desktop/toqueplay/node_modules/@nodegui/nodegui/build/CMakeFiles/CMakeError.log".
ERR! OMG Process terminated: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.30.3 build:addon: `cross-env CMAKE_BUILD_PARALLEL_LEVEL=8 cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nodegui/nodegui@0.30.3 build:addon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
