### ISSUE TITLE
Issue with libicu on Ubuntu

### ISSUE THREAD

**Issue by elilambnz** [nodegui/react-nodegui#4]
Ubuntu 19.04
`npm@6.10.2`
`node@v12.8.1`

Error when running `npm start`:

```
eli@ubuntu:~/react-nodegui-starter$ npm start

> react-nodegui-starter@1.0.0 start /home/eli/react-nodegui-starter
> tsc && qode ./dist/index.js

/home/eli/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.0/qode: error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-nodegui-starter@1.0.0 start: `tsc && qode ./dist/index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-nodegui-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eli/.npm/_logs/2019-08-15T19_53_15_146Z-debug.log
```

Full log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/eli/.nvm/versions/node/v12.8.1/bin/node',
1 verbose cli   '/home/eli/.nvm/versions/node/v12.8.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.8.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-nodegui-starter@1.0.0~prestart: react-nodegui-starter@1.0.0
6 info lifecycle react-nodegui-starter@1.0.0~start: react-nodegui-starter@1.0.0
7 verbose lifecycle react-nodegui-starter@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-nodegui-starter@1.0.0~start: PATH: /home/eli/.nvm/versions/node/v12.8.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/eli/react-nodegui-starter/node_modules/.bin:/home/eli/.nvm/versions/node/v12.8.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/eli/go/bin:/usr/local/go/bin:/home/eli/go/bin
9 verbose lifecycle react-nodegui-starter@1.0.0~start: CWD: /home/eli/react-nodegui-starter
10 silly lifecycle react-nodegui-starter@1.0.0~start: Args: [ '-c', 'tsc && qode ./dist/index.js' ]
11 info lifecycle react-nodegui-starter@1.0.0~start: Failed to exec start script
12 verbose stack Error: react-nodegui-starter@1.0.0 start: `tsc && qode ./dist/index.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/eli/.nvm/versions/node/v12.8.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:203:13)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid react-nodegui-starter@1.0.0
14 verbose cwd /home/eli/react-nodegui-starter
15 verbose Linux 5.0.0-25-generic
16 verbose argv "/home/eli/.nvm/versions/node/v12.8.1/bin/node" "/home/eli/.nvm/versions/node/v12.8.1/bin/npm" "run" "start"
17 verbose node v12.8.1
18 verbose npm  v6.10.2
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error react-nodegui-starter@1.0.0 start: `tsc && qode ./dist/index.js`
23 error spawn ENOENT
24 error Failed at the react-nodegui-starter@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by master-atul** [comment]
Could you try installing libicu-dev on your system ? @elilambnz 

`sudo apt-get install libicu-dev`

I believe this module has a dependency to that. If that solves it, I will update the README.

**Comment by elilambnz** [comment]
Thanks for the fast reply. Yes, this is one of the first things I tried and it unfortunately does not fix the issue.

**Comment by elilambnz** [comment]
If it helps, this is my output for `sudo apt-get install libicu*`

```
eli@ubuntu:~/react-nodegui-starter$ sudo apt-get install libicu*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libiculx63' for glob 'libicu*'
Note, selecting 'libicu4j-java-doc' for glob 'libicu*'
Note, selecting 'libicu4j-java' for glob 'libicu*'
Note, selecting 'libicu55' for glob 'libicu*'
Note, selecting 'libicu63' for glob 'libicu*'
Note, selecting 'libicu-le-hb-dev' for glob 'libicu*'
Note, selecting 'libicu-le-hb0' for glob 'libicu*'
Note, selecting 'libicu-dev' for glob 'libicu*'
Note, selecting 'libicu4j-4.4-java' for glob 'libicu*'
libicu-dev is already the newest version (63.1-6).
libicu63 is already the newest version (63.1-6).
libicu63 set to manually installed.
```

**Comment by master-atul** [comment]
Hey @elilambnz  Can you also try installing `libgtk-3-dev` and try ?

**Comment by gustavsl** [comment]
This is also true for Arch Linux with icu 64.2-1.

**Comment by master-atul** [comment]
Hi @gustavsl  Have you tried installing libgtk-3-dev awell ?

**Comment by master-atul** [comment]
nevermind I am able to reproduce the issue now after uninstalling the installed QT library from my system.

**Comment by master-atul** [comment]
If you want it to work for now, make sure you have qt for linux installed and its bin folder in PATH. I will try and fix it so that it doesnt really need QT to be installed on the system meanwhile.

**Comment by master-atul** [comment]
Alright! Latest version of NodeGUI nodegui@0.1.3 has the fix for linux environment. I had missed few dynamic libraries.
Just take a pull of this repo 
do npm install
and npm start

and it should work!

**Comment by master-atul** [comment]
Closing this issue. Please re open if the issue persists.
